1 // Generated by Selenium IDE
 2  import org.junit.Test;
 3  import org.junit.Before;
 4  import org.junit.After;
 5  import static org.junit.Assert.*;
 6  import static org.hamcrest.CoreMatchers.is;
 7  import static org.hamcrest.core.IsNot.not;
 8  import org.openqa.selenium.By;
 9  import org.openqa.selenium.WebDriver;
10  import org.openqa.selenium.firefox.FirefoxDriver;
11  import org.openqa.selenium.Dimension;
12  import org.openqa.selenium.WebElement;
13  import org.openqa.selenium.interactions.Actions;
14  import org.openqa.selenium.support.ui.ExpectedConditions;
15  import org.openqa.selenium.support.ui.WebDriverWait;
16  import org.openqa.selenium.JavascriptExecutor;
17  import org.openqa.selenium.Alert;
18  import org.openqa.selenium.Keys;
19  import java.util.HashMap;
20  import java.util.List;
21  import java.util.ArrayList;
22  import java.util.Map;
23  public class TestowanieQA {
24    private WebDriver driver;
25    private Map<String, Object> vars;
26    JavascriptExecutor js;
27    @Before
28    public void setUp() {
29      driver = new FirefoxDriver();
30      js = (JavascriptExecutor) driver;
31      vars = new HashMap<String, Object>();
32    }
33    @After
34    public void tearDown() {
35      driver.quit();
36    }
37    @Test
38    public void TestowanieQA() {
39      driver.get("https://www.ultimateqa.com/automation/");
40      driver.manage().window().setSize(new Dimension(1366, 728));
41      driver.findElement(By.linkText("Login automation")).click();
42      driver.findElement(By.id("user_email")).click();
43      driver.findElement(By.id("user_email")).sendKeys("maciek.stygar@gmail.com");
44      driver.findElement(By.id("user_password")).click();
45      driver.findElement(By.id("user_password")).sendKeys("Testowanie2");
46      driver.findElement(By.id("btn-signin")).click();
47      driver.findElement(By.cssSelector(".message-text")).click();
48      driver.findElement(By.cssSelector(".user-name")).click();
49      driver.findElement(By.linkText("My Account")).click();
50      driver.findElement(By.linkText("Profile")).click();
51      driver.findElement(By.id("user_email")).click();
52      {
53        String value = driver.findElement(By.id("user_email")).getAttribute("value");
54        assertThat(value, is("maciek.stygar@gmail.com"));
55      }
56      driver.findElement(By.id("user_first_name")).click();
57      {
58        String value = driver.findElement(By.id("user_first_name")).getAttribute("value");
59        assertThat(value, is("Maciek"));
60      }
61      driver.findElement(By.id("user_last_name")).click();
62      {
63        String value = driver.findElement(By.id("user_last_name")).getAttribute("value");
64        assertThat(value, is("Stygar"));
65      }
66      driver.findElement(By.id("user_profile_attributes_company")).click();
67      {
68        String value = driver.findElement(By.id("user_profile_attributes_company")).getAttribute("value");
69        assertThat(value, is("undefined"));
70      }
71      driver.findElement(By.id("user_profile_attributes_headline")).click();
72      {
73        String value = driver.findElement(By.id("user_profile_attributes_headline")).getAttribute("value");
74        assertThat(value, is("undefined"));
75      }
76      driver.findElement(By.id("user_profile_attributes_timezone")).click();
77      Thread.sleep(undefined);
78    }
79  }
